# vim: ts=2 sw=2 et

name: Sync forks and set policies
on:
  push

jobs:
  sync_forks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Semantic version range syntax or exact version of a Python version
        architecture: 'x64' # Optional - x64 or x86, defaults to x64
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install requests pyyaml
    - name: Sync forks and set policies
      env:
        PAT: ${{ secrets.PAT }}
      run: python ./sync_forks_and_set_policies.py
